# Generated by Django 3.1.6 on 2021-02-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='state_name',
        ),
    ]
